### ISSUE TITLE
University research data support and DPO

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#102]
- would University RDM resources be a better topic page name 
- update the file name to reflect metadata
- update the table headers, possibly combine col1 and col2

suggestion to discuss: include the DPO table on the same page under different header

**Comment by annaasklof** [comment]
I think it is a good idea to include the DPO in the same page as the information on University research data support.

**Comment by YvonneKallberg** [comment]
Regarding DPO, I agree that there's no need for a separate page (as it is now). We need to remember to change the links from plan.md, and tell @jmenglund what the link is so that he can include it in the up-coming research-involving-human-data.md (which will replace all human pages except gdpr-legal-reference.md)

**Comment by annaasklof** [comment]
@elinkronander @YvonneKallberg. 
I started working on this on the branch '102-university-research-data-support-and-dpo'. Feel free to continue the work on this branch. 

Thing mention here that is done:
- new name for the page: University RDM resources 
- update the file name to reflect metadata
- DPO table in the same page 
- changed the link from plan.md

Things left: 
- write an intro text to put under the first heading 'University RDM resources'
- update the table headers, possibly combine col1 and col2

**Comment by YvonneKallberg** [comment]
I made an attempt at adding a intro text, feel free to change.

**Comment by elinkronander** [comment]
Now I've:
* combined col1 and col2 of RDO table
* updated table headers
* some additional small changes
