### ISSUE TITLE
topics/_index.md intro text

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#117]
Not happy with the sentence 'In order to get guidance around a specific research data management topic, you may click on the specific links listen below.'

- 'specific' is written twice
- 'listen' should be 'listed'
- 'you may' sounds like we gracefully allow someone to click

**Comment by LianeHughes** [comment]
'Click on the links below to access guidance about the respective research data management topic'? 

or 

'To access guidance about a given research data management topic, click the respective link below'?

**Comment by LianeHughes** [comment]
(just immediately to mind)
