### ISSUE TITLE
New banner images

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#118]

**Comment by YvonneKallberg** [comment]
I do prefer to see the links in top of page in teal. A question regarding the Q&A 6 Support cards (which I probably should ask in some other issue), are they on purpose of different color? At least for me the Support is in grape and the Q&A is in teal.

**Comment by annaasklof** [comment]
Yes I did the cards in two different colors to spice it up a bit. I also thought that would make it clear that the boxes are displaying content of two different types. But that could ofcourse be changed.

**Comment by YvonneKallberg** [comment]
Just making sure that it is displayed as intended, I have no objections.
