### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#136]
[README.md](https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/README.md)
- [x] modify motivation and background
- [x]  add licence header, state which licence applies to which part -  code  and content

[current-resources-list.md](https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/current-resources-list.md)
- [x] move to an issue

Remove content folders
- [x] [agreements](https://github.com/ScilifelabDataCentre/RDM-guidelines/tree/main/content/agreements)
- [x] [temp_init_files](https://github.com/ScilifelabDataCentre/RDM-guidelines/tree/main/content/temp_init_files) see comment below

**Comment by YvonneKallberg** [comment]
But do not remove temp_init_files until we are sure that old human data files have been captured in the 2 new files.

**Comment by elinkronander** [comment]
wit until human data topic is expanded
