### ISSUE TITLE
Add element-boxes to relevant pages

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#138]
Add element-boxes with different colors based on type of element 
see blue info-box for example https://fega.nbis.se/submission/preparing-data.html

This could be used for disclaimer on human data page for example

**Comment by annaasklof** [comment]
I have added an alert on the page "GDPR - legal reference". I have also added an alert on the human data page in the branch "3-human-data-page". 

Is there any more places where we would like an alert? 

https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by elinkronander** [comment]
I think the red box on "3-human-data-page" is a bit too red so I changed it to a yellow "warning"-box
