### ISSUE TITLE
Verify that all necessary content from previous resources is contained in RDM site

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#145]
#DM pages/resources at SciLifeLab

- [x] #178

- [x] SLL Data guidelines <https://scilifelab-data-guidelines.readthedocs.io/en/latest/docs/index.html>
should covid specific information be moved to covid portal? @YvonneKallberg 

- [ ] ENA submission tutorial SARS-CoV-2 <https://www.covid19dataportal.se/support_services/tutorial_ena/tutorial_ena_intro/> 
#171

- [ ] other text from covid-19 portal?
#171

- [x] ENA metadata templates https://drive.google.com/drive/folders/12VxEMdvPJ3ZrkMgEnI_wAnamDQbR43B-?usp=sharing - (restricted access NBIS DM team google drive)

- [x] NBIS DM introduction page Data Management Introduction <https://nbis.se/infrastructure/data-management/dm-introduction.html> 

- [x] Universities guidelines & policies <https://scilifelab.atlassian.net/wiki/spaces/SDMCS/pages/932970513>  (also SND Basecamp, more updated? https://3.basecamp.com/3853863/buckets/5947445/vaults/2397292050) 

- [x] RDMkit Swedish page RDMkit  (including list of Research Data Offices) <https://rdmkit.elixir-europe.org/se_resources.html>

- [ ] YouTube playlist https://www.youtube.com/playlist?list=PL1nnHOyxN_WdqnzLqbmWJz_i0f2anT9cS
#169 

- [ ] DSW appendix <https://github.com/ScilifelabDataCentre/dsw-appendix>
#170

- [x] SciLifeLab Repository guidelines <https://www.scilifelab.se/data/repository/submission/>
the repository guidelines can reside where they are

- [ ] SLL Human data page <https://www.scilifelab.se/data/humandata/>
see #166 

- [ ] SLL GDPR for Life Science data <https://www.scilifelab.se/data/gdpr-for-life-science-data>
see #172

**Comment by YvonneKallberg** [comment]
DSW appendix have information (might be outdated though) about data and file types, which I don't think is included anywhere: https://dsw.scilifelab.se/appendix/dataset_documentation/. 

Note to self: Our knowledge models refers to this page, and I've kept them for now, but if we decide to include this in the guidelines, remember to update the KMs.

**Comment by elinkronander** [comment]
look at all resources together at next editorial group meeting

**Comment by elinkronander** [comment]
I've created new issues for all remaining resources apart from the human data guidelines confluence page (top resource)

**Comment by elinkronander** [comment]
I've now created an issue for the human data guidelines as well and will close this one and the resources separately.
