### ISSUE TITLE
Update link to figshare.scilifelab.se

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#152]
At least https://data-guidelines.scilifelab.se/data-life-cycle/share/ under Genomics expandable text has a reference to this repo and the link should be updated to new url. Might be other pages as well, hence do a search and replace.

**Comment by YvonneKallberg** [comment]
Hmm, should we though, @annaasklof? All pages link to https://www.scilifelab.se/data/repository/ which might be better than to link directly to https://figshare.scilifelab.se since it is about depositing rather than search/reuse. Pages concerned are:
- share.md
- research-involving-human-data.md

**Comment by annaasklof** [comment]
Indeed, links to https://www.scilifelab.se/data/repository/ should preferable be kept as is. However, if we have any linksscilifelab.figshare.com  they can be changed to figshare.scilifelab.se/.

**Comment by YvonneKallberg** [comment]
I couldn't find any such links, will close this issue.
