### ISSUE TITLE
New topic: Publishing human data

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#166]
Move and update this information: https://www.scilifelab.se/data/humandata/

The text "Repositories for publishing human data" on the page: https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topics/research-involving-human-data.md could also be moved to this new page.

**Comment by elinkronander** [comment]
Hanna and Markus will give input to Anna

**Comment by elinkronander** [comment]
Work is progressing, next meeting Feb 10.
