### ISSUE TITLE
Update policies page

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#17]
https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/policies.md

The list is taken from https://scilifelab.atlassian.net/wiki/spaces/SDMCS/pages/932970513/University+guidelines+and+policies

1. Check that links are still valid
2. Check if there are other universities who now has policies of research data guidelines
3. Decide which universities to include, host universities or all we can find?
4. Are there any pages that should link to this page, planning perhaps?

**Comment by KatarinaOjeforsStark** [comment]
I self assigned myself for this topic

**Comment by elinkronander** [comment]
Possibly change from pdf to html page. Think about this

**Comment by elinkronander** [comment]
see #64

**Comment by elinkronander** [comment]
I will close this issue since there is no policies page any more.
