### ISSUE TITLE
GDPR dictionary

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#176]
Ask Mattias or Markus to provide GDPR dictionary file
- consider to add it as an "accordion"/expandable card on GDPR page
- could existing text be shortened and link to dictionary instead

**Comment by elinkronander** [comment]
add as a topic page on a new branch

**Comment by annaasklof** [comment]
The dictionary has now been added here: /content/temp_init_files/gdpr-and-ethical-review-terms.md. Do we want to make it a new topic?

**Comment by YvonneKallberg** [comment]
- [ ] Update links in page /topics/research-involving-human-data/
