### ISSUE TITLE
Broken link on sharing phase page

### ISSUE THREAD

**Issue by LianeHughes** [ScilifelabDataCentre/RDM-guidelines#180]
/meta-data-templates/metadata_template_sewage_ERC000036.xlsx shows 404 not found.

**Comment by annaasklof** [comment]
Correct link: /meta-data-templates/metadata-template-sewage-ERC000036.xlsx

**Comment by elinkronander** [comment]
might be fixed by #166

**Comment by annaasklof** [comment]
This link is also on the topic Metadata page.
