### ISSUE TITLE
Add resources page

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#190]
- [ ] Create a resources page with a list of resources in different categories 

maybe:
training resources
general resources
tools

- [ ] Define and document categories and rules.

- internal pages should be referenced in text, not under resources
- resources should only be added to the list if mentioned on a content page

- [x] Define filtering tags for resources together with Sara and Katarina. @LianeHughes 
 
- [x] #201

**Comment by elinkronander** [comment]
We need to settle on what metadata we want to collect for each resource. This might differ between the different resource categories.
@elinkronander look into what is used by Tess and recommendations in FAIRifying your training material guide etc.

**Comment by YvonneKallberg** [comment]
When renaming from Resources and Training to Resources, I collected all resources mentioned in a [spreadsheet](https://docs.google.com/spreadsheets/d/1aaMAR2i6gKbe4eV0qXxckAO17ZSY5Ctrrsrfuvje0Es/edit?usp=sharing) (as an inventory attempt)

**Comment by elinkronander** [comment]
Sara will provide list of desired tags and categories in April
- recommendation to use 5 tags per category
- maximum of 4 categories

**Comment by LianeHughes** [comment]
Started to work on a filtering functionality for training resources. The code still needs a lot of work. Going to work on the basis of having 3 filters (think they are as below - need to confirm):
- Type of resource (training...etc.)
- Level (difficulty)
- Stage in RDM cycle

**Comment by LianeHughes** [comment]
(for now, I've named it 'Training' in this branch, but we can rename to resources when we've finalised details)

**Comment by YvonneKallberg** [comment]
Link to our [notes](https://scilifelab.atlassian.net/wiki/spaces/SDMCS/pages/2495971366/2023-05-31+notes) where we discussed resources, mentions e.g. the probable types

**Comment by elinkronander** [comment]
- [ ] Classify resources into categories 5/7

**Comment by YvonneKallberg** [comment]
I've made an updated inventory of resources listed, moved resources that should not be there into text (branch/PR #257) and transformed into the agreed format. In the [table](https://docs.google.com/spreadsheets/d/1aaMAR2i6gKbe4eV0qXxckAO17ZSY5Ctrrsrfuvje0Es/edit#gid=299488090), I've highlighted in yellow the things that is unclear, and added a comment in separate column. For GDPR related rows (last in table), I didn't add a description since I was unsure if they should remain as resource or be moved into text.

**Comment by elinkronander** [comment]
Internal meeting notes https://scilifelab.atlassian.net/wiki/spaces/SDMCS/pages/2495971366/2023-05-31+notes

**Comment by YvonneKallberg** [comment]
Action points from advisory meeting 2023-08-30:

- [ ] COVID portal resource should change name to Swedish pathogens portal
- [ ] Suggestion to spell out content provider abbreviations on the detail card (e.g. SND)
- [ ] Find out if there's possibility to automated script checking dead links
