### ISSUE TITLE
metadata template link

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#199]
Page https://data-guidelines.scilifelab.se/topics/metadata/ has a faulty link for the sewage metadata template. However, I think that we should change the name of the template rather than changing the link: Current name is metadata-template-sewage-ERC000036.xlsx and since the other templates uses '_' (and the current link as well), we should rename it to metadata_template_sewage_ERC000036.xlsx

**Comment by annaasklof** [comment]
This relates to issue #180
