### ISSUE TITLE
Fix logo to adhere to SciLifeLab

### ISSUE THREAD

**Issue by KatarinaOjeforsStark** [ScilifelabDataCentre/RDM-guidelines#2]
Fix logo to adhere to SciLifeLab- set up meeting with Liane Hughes DC for this

**Comment by elinkronander** [comment]
The tagline "knowledge hub..." should be updated to refer to the focus of life science research in **Sweden**

**Comment by LianeHughes** [comment]
Hopefully the above pull request is sufficient to resolve this issue
