### ISSUE TITLE
Display of internal/external contributors

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#213]
On the meeting on April 12 we discussed to change the way we planned to display contributors on this page: https://data-guidelines.scilifelab.se/about/contributors/. 
The idea is to display contributors as editorial group, advisory group and a third 'group' covering all other contributors. This third group would include internal contributors that are not part of either editorial or advisory group and external contributors.

**Comment by elinkronander** [comment]
In the contributors section, everyone from the editorial and advisory groups will also be included
