### ISSUE TITLE
Link to AIDA data sharing policy 

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#235]
Feedback from Data platform launch:
https://datahub.aida.scilifelab.se/sharing/
"Regarding RDM guidelines, have you considered linking the AIDA Data Sharing Policy in there? It's a community resource developed by ~50 partners in Swedish healthcare, academia and industry for best practices in legal and ethical sharing medical data for reserach and innovation, with reference to real life examples and official law text"

**Comment by elinkronander** [comment]
Add a section about AIDA data hub on sharing human page under sharing personal data title
