### ISSUE TITLE
Add topic on organizing day-to-day?

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#236]
Feedback from data platform launch:
"Another thought regarding the RDM guidelines: It seems it could be useful with a topic on very practical considerations on how to organize your day-to-day work.

Often there is a big gap between the idealized way to publish data & metadata, but often the challenge starts in how to have a good structure (even folder structure etc), that makes sure every experiment done is reproducible etc.

Resources could be links to articles like this one, which I know has been referenced in SciLifeLab courses: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424# "

At least make sure that the resource is added to appropriate phase, I guess?

**Comment by YvonneKallberg** [comment]
Decided at editorial meeting to put it under related guidelines

**Comment by YvonneKallberg** [comment]
Not sure where to add this. First of all, do we really want a separate topic of something that covers plan, collect, process and analysis? Or, do we add reference to the paper to one or more phases? Which ones? If so, do we just add it under Resources or write a short text and put it in the text in the respective phase page?

**Comment by annaasklof** [comment]
I agree that this should not be a new topic as it is covered by some phases. Rather reference the paper where we see fit.

**Comment by elinkronander** [comment]
Write a short text and put it in the text in the respective phase page, probably plan and collect
