### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#25]
In the metadata header of each page, we have the possibility to set the visibility of the left-hand table of content. In pages with only one heading, (e.g. research-data-office.md), it looks weird, should we perhaps remove them in this case (i.e. set toc to False)? If so, there's a need to check all pages (as current default is toc set to True). Also, if so, add instructions on this in the internal-contribution.md page.

**Comment by elinkronander** [comment]
If possible it would be nice to have the data-life-cycle wheel above/below the left hand toc for the data-life-cycle pages

**Comment by LianeHughes** [comment]
I currently cannot see anything with just one header. Unsure what else is needed on this issue

**Comment by elinkronander** [comment]
Add DLC-wheel to TOC in phase pages

**Comment by elinkronander** [comment]
Let's leave that for now, I'll create a new issue for that
