### ISSUE TITLE
Update info about FEGA

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#259]
For now we still have these guidelines regarding sharing human data: https://data-guidelines.scilifelab.se/topics/sharing-human-data/ that says that 'Do you plan to submit data to FEGA Sweden? While waiting for the repository to become operational, you may want to create a metadata record in SciLifeLab Data Repository (see below). This will give you a DOI to put in your research article. Once your data has been released in FEGA Sweden, our data management support team will help you update your metadata record with appropriate information.'. 

The guidelines will need to be edited once FEGA goes into production.

**Comment by YvonneKallberg** [comment]
FEGA is mentioned in several places, and also on https://data-guidelines.scilifelab.se/data-life-cycle/share/. I've asked FEGA Helpdesk for assistance

**Comment by elisavettorstensson** [comment]
As the FEGA Sweden will be operational soon, it would be good to update the information regarding the sharing of personal data on the page: https://data-guidelines.scilifelab.se/topics/sharing-human-data/#sharing-personal-data

After a conversation I had with the rest of the FEGA Sweden Team, we decided which parts we would change on the previous page.
