### ISSUE TITLE
Add Chalmers guide on data handling 

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#278]
Add this to university resources https://3.basecamp.com/3853863/buckets/5947445/uploads/6520221160 
try to find a stable link

**Comment by YvonneKallberg** [comment]
I tried to find a stable link at Chalmers but it is only available on their intranet, the closest I got was https://intranet.chalmers.se/verktyg-stod/forskning-nyttiggorande/publicera-och-analysera-forskning/hantera-forskningsdata/ and I'm not sure that this 'styrdokument' is linked there. And, SND requires login as well, no? Not sure how to handle this.

**Comment by elinkronander** [comment]
I have reached out to the original poster on basecamp to ask for a link. We might want to update the link to the RDO as well but I hope to get some feedback on that as well.
