### ISSUE TITLE
update contribution guidelines

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#288]
update the internal contribution guidelines [internal-contribution.md](https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/internal-contribution.md) to include information about resources
- what is a resource 
- description of resource types
- how to add a resource

**Comment by YvonneKallberg** [comment]
I will make an attempt but might need help regarding how to add a resource :-)

**Comment by annaasklof** [comment]
@YvonneKallberg I'm happy to hep with that part :)
