### ISSUE TITLE
Add tools

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#294]
We see the need of adding more tools (hjälpmedel) to the resources on the site. For example, protocols.io, SUNET drive.

**Comment by YvonneKallberg** [comment]
OpenRefine, see also initial seed from Training and tools workgroup

**Comment by YvonneKallberg** [comment]
Ask advisory board on the scope / which tools to include or not, i.e. when is a tool a data management tool?
