### ISSUE TITLE
Human data page

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#3]
The following is being considered for the MVP:

Two topic pages related to human data:

* "Research involving human data"
* "GDPR – Legal reference"

These two document will replace the current topics "Human data PI" and "Sensitive data". The topic pages "General processing agreements" and"Human data bioinformatician" can probably be removed.

# Research involving human data

- [x] Create document `research-involving-human-data.md`
- [x] Draft a document structure
- [ ] Add relevant content from https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/sensitive-data.md
   * The "Clarifications and comments" section is probably better to add to the legal reference page instead
- [ ] Add relevant content from https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/human-data-PI.md
- [ ] Add relevant content from "Human data bioinformatician"
- [x] Remove any information specific to NBIS
- [x] Add links to external resources where relevant:
   - [x] https://rdmkit.elixir-europe.org/human_data
   - [x] https://fega.nbis.se
   - [x] https://snd.gu.se/en/manage-data/plan/research-material-with-personal-data
- [ ] Adapt content to align with the new document structure

# GDPR – legal reference

 - [x] #107
 - [x] Add relevant content from https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topics/human-data-legal-ref.md
 - [ ] Add relevant content from https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/human-data-PI.md
 - [x] Remove any information specific to NBIS

**Comment by nicjar** [comment]
Consider how to relate to https://rdmkit.elixir-europe.org/human_data

**Comment by YvonneKallberg** [comment]
Existing pages (in repo):

- https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/sensitive-data.md
- https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/general-processing-agreements.md
- https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/human-data-PI.md
- https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/human-data-bioinformatician.md

Existing pages (outside):

- SciLifeLab Data Repository guidelines [SciLifeLab Data Repository Submission Guidelines](https://www.scilifelab.se/data/repository/submission/)
- SLL Human data page [Human Data](https://www.scilifelab.se/data/humandata/)
- SLL GDPR for Life Science data [GDPR for Life Science data](https://www.scilifelab.se/data/gdpr-for-life-science-data))

**Comment by YvonneKallberg** [comment]
Note that page plan.md refers to sensitive-data.md, so update there if a new page is created.
