### ISSUE TITLE
Review repo README and contribution instructions

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#324]
- review README file and instructions on how to contribute to make sure they cover everything needed and is up to date

**Comment by elinkronander** [comment]
Consider signed commits instructions

**Comment by elisavettorstensson** [comment]
In the README file in the Project goals, I believe that the data.scilifelab.se should be linked to the website; I did it, and I committed and pulled it to branch #324.

**Comment by elisavettorstensson** [comment]
After reviewing the README file, I believe that it was quite easy to follow the instructions. However, I did not understand this meaning or what I had to do in this case, and I did not succeed with this part: It was in the description of testing locally and installing Hugo. I have installed Hugo, I believe, but when I could not figure out where I was going to write this command : "Once Hugo is installed, simply run the following command **in the repository root (RDM-guidelines) directory**:

$ hugo serve " 
What is the repository root directory ? I tried this command in git bush when I was in the directory of RDM-guidelines but I received the message:  bash: hugo: command not found. I use windows.

**Comment by elinkronander** [comment]
Write down the criteria for a resource in the internal contributions page. 
Is it OK to add a resouce on the resource page only or does it need to be linked from a page as well?

**Comment by YvonneKallberg** [comment]
I've tried to clarify how to add a resource in the internal contribution page, please have a look.

**Comment by elisavettorstensson** [comment]
This is a minor issue, but in the ReadMe file -> look at the bullet points ->some sentences have full stops, and others do not. Is there any specific reason for that? I can fix it if you want, with or without full stops.

**Comment by elisavettorstensson** [comment]
When I read the text in the ReadMe file, there is in the project goals this website [data.scilifelab.se](https://data.scilifelab.se/). Do we want to refer to this website? It says hosted ... it might be this website. I wanted only to double control this.

**Comment by elisavettorstensson** [comment]
In step 3a, when I look at the preview of the visual studio, it appears like this: Pencil icon :pencil2: ... is it ok to have it not as an icon-pencil but more as a code?

**Comment by elinkronander** [comment]
> When I read the text in the ReadMe file, there is in the project goals this website [data.scilifelab.se](https://data.scilifelab.se/). Do we want to refer to this website? It says hosted ... it might be this website. I wanted only to double control this.

Change title from project goals to "Purpose" and change to something like: hosted by SciLfieLab Data Centre and listed as a service at the data platform

**Comment by elisavettorstensson** [comment]
I changed the title to "Purpose", and I changed the content a bit.
