### ISSUE TITLE
Consider citation information for the RDM guidelines 

### ISSUE THREAD

**Issue by LianeHughes** [ScilifelabDataCentre/RDM-guidelines#325]
We should make it clear how people can cite the resource itself, and the GitHub.

RRID's should be used for the resource https://scicrunch.org/resources, and we can have a page for citations on the main site that shows it. Should also have FAIRsharing shown there, but considered better practice to use RRID rather than DOI for that.

For the Github, we should add a citations file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#, and we should get a Zenodo reference to use for DOI.

**Comment by YvonneKallberg** [comment]
Guessing that the [draft PR by Senthil](#342) is part of this, we should ask advisory board if they should be included or only editorial board

**Comment by elinkronander** [comment]
citation: editorial + advisory
