### ISSUE TITLE
Resources filters, order of options 

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#340]
In issue #247 Resource page, a temporary hack was made (in layouts/resources/list.html) so that the left-hand filters for Phases and Levels are in more logical order rather than alphabetical order (follow the phases of the life cycle, basic level first). The fix requires that the 2 first resources in resources.json file doesn't change, and since this is not an optimal solution we need to find a more sustainable one. 

The solution should still read all resources, and make them unique, so that if there is a typo this will be seen by the appearance of a new/additional filter option. However, we need some code for doing the sorting in the desired way. Perhaps we can match the variables $level and $phase against predefined arrays with desired order of known levels and phases, and only print those that do not match (after the predefined arrays are written for each filter)?

**Comment by annaasklof** [comment]
I have started working on this. For now I have added an array with the phases in the desired order from which the filter options take their names. However, this solution does not include the latter part of the above description (i.e.  if there is a typo in a newly added resource that will not be seen by the appearance of a new/additional filter option).

**Comment by YvonneKallberg** [comment]
Given that phases likely is a fixed list, and that levels currently are not used as filter, we only need to catch typos. Is it possible to throw an error code, so that Hugo, when building the site, fails the build and give an error message stating which row is offending (i.e. which row has the typo)? 

Thinking about it, I realise that we probably should add more such checks when it comes to resources, for example making sure that all mandatory fields exist, and that all fields with a 'controlled vocabulary' are correctly filled...
