### ISSUE TITLE
TOC links to wrong place

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#348]
In table of contents, whenever it contains a header that is linked, this will be the link in the TOC, not link to the position in page, e.g. in [sharing human data](https://data-guidelines.scilifelab.se/topics/sharing-human-data/), all the repositories are linked in the header and if I click on FEGA Sweden in TOC I go to [fega.nbis.se](https://fega.nbis.se/) and not to the text about FEGA on the page itself (https://data-guidelines.scilifelab.se/topics/sharing-human-data/#fega-sweden doesn't even work when pasting the link in browser manually).

**Comment by elinkronander** [comment]
Remove link from title, add link in text description instead
