### ISSUE TITLE
Resources material

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#365]
Go through all material listed on the resources page. We most likely need to remove some training material resources. 

- Need to ensure that courses and training material is separated

- Need to ensure that resource links are updated (outdated canvas pages should not be there, either update each semester or link to other, more stable/sustainable, page)

**Comment by elinkronander** [comment]
Intro to DM practices - keep canvas landing page
Programming formalisms - check for more persistent link
Make sure titles are descriptive enough (BAS, R)
