### ISSUE TITLE
Make shorter titles in the Resources 

### ISSUE THREAD

**Issue by elisavettorstensson** [ScilifelabDataCentre/RDM-guidelines#367]
On the page https://data-guidelines.scilifelab.se/resources/ we can try to make shorter titles in order to be in one row only (not 2 or 3 rows for a title).

**Comment by annaasklof** [comment]
Keep the original title to be able to use that one on the cards. This means that each resource will have two titles "title" and "short title".

**Comment by YvonneKallberg** [comment]
Related to PR #368

**Comment by annaasklof** [comment]
Solved in another branch. https://github.com/ScilifelabDataCentre/RDM-guidelines/pull/374
