### ISSUE TITLE
Stockholm University Figshare Repository

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#376]
We could add the Stockholm University Figshare Repository as an example under the section "Other data" on the sharing phase page. https://data-guidelines.scilifelab.se/data-life-cycle/share/

**Comment by elinkronander** [comment]
Should we add SND - DORIS https://snd.se/en/catalogue/search?
Maybe a new table in the university resources page https://snd.se/en/catalogue/search with repositories would be an alternative if many universities have them

**Comment by elinkronander** [comment]
Decision: Add both SU and SND to "Other data" on the sharing phase page. https://data-guidelines.scilifelab.se/data-life-cycle/share/
