### ISSUE TITLE
Add link to DUO 

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#379]
We can potentially add a link to the Data Use Ontology: https://www.ebi.ac.uk/ols4/ontologies/duo. 

Potentially add on the page: https://data-guidelines.scilifelab.se/data-life-cycle/share/

**Comment by elinkronander** [comment]
Look into if DUO is only used sor sensitive data and then decide where to mention it.
Consider also pages: metadata and working with human data pages.

**Comment by elinkronander** [comment]
https://obofoundry.org/ontology/duo.html#:~:text=DUO%20is%20an%20ontology%20which,of%20users%2C%20or%20intended%20usage

**Comment by annaasklof** [comment]
I found the description here: https://github.com/EBISPOT/DUO?tab=readme-ov-file#how-did-duo-come-about

"The (GA4GH) Data Use Ontology (DUO) includes terms describing data use conditions, particularly for research data in the health/clinical/biomedical domain."

**Comment by annaasklof** [comment]
On meeting 2024-09-11 it was decided to not put DOU on any of the existing pages. However, it can be put on a future page.
