### ISSUE TITLE
Reorder topics

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#381]
Which order should the topics be displayed

**Comment by elinkronander** [comment]
- [ ] check which topics are most clicked on

**Comment by elinkronander** [comment]
on topics page, use alphabetical order

**Comment by annaasklof** [comment]
Most visited topics during the period of 2024-01-01-2024-05-31

1. human-data (sharing-human-data, research-involving-human-data and gdpr-ethical-review-glossary) 
2. university-rdm-resources
3. data-transfer
4. metadata
5. readme-files
6. fair-principles
7. what-is-rdm
