### ISSUE TITLE
Reuse symbols from RDLC wheel

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#386]
We might want to reuse the symbols from the research data life cycle wheel from RDMkit. These symbols could be used on the resources page or elsewhere. 

Plan - https://icons.getbootstrap.com/icons/pencil-square/
Collect - 
Process - https://icons.getbootstrap.com/icons/pc-display-horizontal/
Analyse - https://icons.getbootstrap.com/icons/bar-chart-fill/
Preserve - https://icons.getbootstrap.com/icons/server/
Share - https://icons.getbootstrap.com/icons/share-fill/
Reuse - https://icons.getbootstrap.com/icons/arrow-repeat/, https://icons.getbootstrap.com/icons/arrow-repeat/

**Comment by elinkronander** [comment]
Send an email to Johan Inganni and ask about the symbols in the microsite https://www.scilifelab.se/data-driven/about/ddls-microsite/

**Comment by YvonneKallberg** [comment]
Det finns subscription, single purchase, och attribution, om man följer länkarna från RDMkit's kit https://thenounproject.com/ELIXIRCommunications/kit/rdmkit/. Tittar man på vad som gäller för hela Noun project finns Free, Icon Pro och Creator Pro. För Creator Pro är det tydligt att man får göra editeringar, t ex ändra färg, men övriga är oklart https://thenounproject.com/pricing/.
