### ISSUE TITLE
add links to research-data-office

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#39]
Linköping and Naturhistoriska is still missing good pages to link to.

(Probably not because we haven't found them but because they don't exist)

**Comment by elinkronander** [comment]
SLU https://www.slu.se/dms

**Comment by KatarinaOjeforsStark** [comment]
Linköping seem to have data management through the library https://liu.se/en/article/forskningsstod

**Comment by KatarinaOjeforsStark** [comment]
Örebro has a DAU https://www.oru.se/english/research/research-support/starting-up-your-research-project/data-management-plan-components/do-you-need-help-with-your-research-data/

**Comment by elinkronander** [comment]
Linneuniversitetet: https://lnu.se/en/medarbetare/researcher/researcher5/research-data/

**Comment by elinkronander** [comment]
see #64

**Comment by elinkronander** [comment]
Linköping still needs to be added
