### ISSUE TITLE
Search function - multiple words

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#391]
The search function on the resources page can not handle multiple words as search terms. I.e. searching for "data stewardship" in the tools tab renders no result while searching for "data" or "Stewardship" shows the Data Stewardship Wizard card. 
Try adding the entire title as search term to see if this solves the problem.

**Comment by annaasklof** [comment]
I checked the resources ( resources.json) and all resources have their name listed as a search tag. So that is not what's causing this problem.
