### ISSUE TITLE
add different colors to resource tabs

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#393]
To improve the visual impression even more of the resources page, different colors for the different tabs could be used

**Comment by elinkronander** [comment]
- change the order of colors to match landing page boxes: "green, purple, blue"
- try to change card titles to corresponding dark version of tab color
- try to change border color to corresponding dark version of tab color

**Comment by YvonneKallberg** [comment]
- I've changed the order of colors on the tabs
- I've changed the card titles so they match the respective tab colors
- I have **not** managed to change border color. What I can do is change background colors on the cards, but not sure if it looks good: 

![training-card](https://github.com/user-attachments/assets/b7912611-502f-4381-a247-4657967fcd3b)
![guidance-card](https://github.com/user-attachments/assets/a0f8e3df-cb6c-4137-be65-004e1cd64dc2)
![tools-card](https://github.com/user-attachments/assets/028df6af-6a92-4e3b-8d2e-71a2b148ad84)

**Comment by YvonneKallberg** [comment]
* Troligen för dålig kontrast att ha orden Training, Guidance, Tools, i mörkare färg än bakgrund -> återgå till hur det var förut
* Ändra korten så att ramen blir i samma färg som short_titel, och återställ bakgrunden till hur det var förut
* Anna gör ett försök att skifta stora ramen, så att den återspeglar färgen på den aktiva resurstypen
* Färgordningen stämmer förvisso med ordningen på framsidan, men blir ändå missvisande att inte Training är grape, då det är så på framsidan. Vi föreslår att Training är grape, Guidance är aqua och Tools är lime.
