### ISSUE TITLE
update about RDM guidelines page

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#41]
https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/about/_index.md
* make sure data life cycle is two words not one (lifecycle)
* verify link to Data Centre and possibly add link to data platform as well
https://www.scilifelab.se/data/
https://www.scilifelab.se/community-pages/systems-data/
https://data.scilifelab.se/

**Comment by LianeHughes** [comment]
Wondered whether it might be good to have the logos for the organisations in the about page, in place of the headers?
