### ISSUE TITLE
Go through links at university resources page

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#412]
Some links that are not correct:
- [x] [GDPR at SU](https://www.su.se/english/staff/organisation-governance/legal-information) 
- [x] UU [General Data Protection Regulation (GDPR) – how it works](https://mp.uu.se/en/web/info/stod/dataskyddsforordningen)
- [ ] Swedish Research Council - [Good research practice (2017)](https://www.vr.se/english/analysis/reports/our-reports/2017-08-31-good-research-practice.html)
- [x] SU [Policy for open science](https://www.su.se/medarbetare/organisation-styrning/styrdokument-regelboken/forskning/policy-f%C3%B6r-%C3%B6ppen-vetenskap-1.628358)

Could also check if the PDFs are the latest versions and if the Universities missing policys in the tables have a policy now.

**Comment by elisavettorstensson** [comment]
Regarding this page: [GDPR at SU ](https://medarbetare.su.se/en/our-su),it is linked to a page that refers to staff news, staff regulations, and other irrelevant topics. If we want to connect it to more relevant GDPR content, I found this page: [Personuppgifter/GDPR](https://medarbetare.su.se/vart-su/styrning/regelboken/personuppgifter-gdpr) (it is in Sweden). The English version is the here : https://medarbetare.su.se/en/our-su/governance/rules--regulations/processing-of-personal-data though it is currently under construction. 

Another page that is interesting is the following: https://medarbetare.su.se/stod-och-service/internutbildningar/forskning/gdpr-and-personal-data-in-research-what-to-think-of

If we want to provide users with a communication channel to contact the legal department, we can also include a link to this page: https://medarbetare.su.se/en/support-and-service/legal. The data protection officer is the key person who can assist with GDPR-related issues.

**Comment by elisavettorstensson** [comment]
Regarding UU and GDPR we can link to the following page: https://www.uu.se/en/students/your-rights/examination/gdpr

**Comment by elisavettorstensson** [comment]
Regarding the Swedish Research Council - [Good research practice (2017)](https://www.vr.se/english/analysis/reports/our-reports/2017-08-31-good-research-practice.html).There is an information box in the website that informs the reader that the content on "Good Research Practices" will be updated in autumn 2024. It does not appear to be updated yet. We can keep an eye on it over the next few months to see if it gets updated.

**Comment by elisavettorstensson** [comment]
Regarding SU [Policy for open science](https://www.su.se/medarbetare/organisation-styrning/styrdokument-regelboken/forskning/policy-f%C3%B6r-%C3%B6ppen-vetenskap-1.628358). I have found a new page that is more associated with the topic and is the following: https://medarbetare.su.se/en/our-su/governance/rules--regulations/research/open-science-policy I have also checked the provided pdf file and it is updated, it is valid from the 2024-10-02.

**Comment by elisavettorstensson** [comment]
Regarding **UU and Open Science policy** I could not find a specific policy, but they have a site where they analyze open science. If we want to use this link, it is as follows: https://www.uu.se/en/library/publish/open-science

**Comment by elinkronander** [comment]
The Swedish version can be found here  https://www.vr.se/english/just-now/news/news-archive/2024-10-02-new-edition-of-the-swedish-research-councils-publication-good-research-practice.html here but I think we should wait for the English one. On Oct 15, 2024 13:12, elisavettorstensson ***@***.***> wrote:
Regarding the Swedish Research Council - Good research practice (2017).There is an information box in the website that informs the reader that the content on "Good Research Practices" will be updated in autumn 2024. It does not appear to be updated yet. We can keep an eye on it over the next few months to see if it gets updated.

**Comment by YvonneKallberg** [comment]
I've created a separate issue #415 so that we can keep an eye out for the English version
