### ISSUE TITLE
Institutional repositories

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#433]
Add a new heading to the Share phase page called "Institutional repositories". Under this heading we can collect all of the institutional repositories now under "Recommended discipline-specific repositories">"Other data".

**Comment by annaasklof** [comment]
See also issue #434

**Comment by elisavettorstensson** [comment]
**KTH** recommends the following: [KTH Zenodo community ](https://zenodo.org/communities/kth/records?q=&l=list&p=1&s=10&sort=newest), SND and re3data.org,

**Comment by elisavettorstensson** [comment]
**Linköping University** does not seem to offer an institutional repository

**Comment by elisavettorstensson** [comment]
**Linnaeus University** recommends the following repositories: SND, Zenodo and Figshare

**Comment by elisavettorstensson** [comment]
**Lund University** recommends the following: SND, Zenodo, OSF and re3data.org,

**Comment by elisavettorstensson** [comment]
**SLU** does not seem to have an institutional repository. It recommends SND and Re3data.org

**Comment by elisavettorstensson** [comment]
**Umeå University** recommends SND, Zenodo and Figshare

**Comment by elisavettorstensson** [comment]
**Göteborg Universitet** does not seem to offer an institutional repository

**Comment by elisavettorstensson** [comment]
Uppsala University does not seem to offer an institutional repository. However here is the[ list ](https://www.uu.se/en/staff/gateway/research/research-handbook/research-data/publish-data )of the alternative repositories that they suggest.

**Comment by elisavettorstensson** [comment]
From my review, I can comment that the majority of universities do not have institutional repositories, except for KI, which has the KI Data Repository. KTH and SU recommend their KTH Zenodo and  SU Figshare communities, respectively. In most cases, it seems that they recommend SND, Re3data.org, and Zenodo.
