### ISSUE TITLE
Information on README files

### ISSUE THREAD

**Issue by annaasklof** [ScilifelabDataCentre/RDM-guidelines#52]
It could be a good idea to include information on both README  in the RDM guideline content. Today we have some short information and an example files on the SciLifeLab Data Repository submission guidelines: https://www.scilifelab.se/data/repository/submission/. This could perhaps function as inspiration/starting point for this content.

This issue is also relevant for issue: Information on manifest files #68

**Comment by annaasklof** [comment]
I have now separated this into two issues as discussed on the meeting.

**Comment by annaasklof** [comment]
This will be a new topic. 

After meeting on December 7 it was suggested that this page include some short information about manifest files, instead of having a separate topic for manifest files.

**Comment by YvonneKallberg** [comment]
Came across a page about README files that could be of inspiration/source if we want to have something general about how to write readme's and not only in context of data repository. [https://rdm.elixir-belgium.org/data_documentation#readme-file](https://rdm.elixir-belgium.org/data_documentation#readme-file). Also this one from library carpentry: [https://librarycarpentry.org/lc-fair-research/05-reusable/index.html#directory-structures-and-readme-files](https://librarycarpentry.org/lc-fair-research/05-reusable/index.html#directory-structures-and-readme-files)

**Comment by YvonneKallberg** [comment]
Guide on how to write a README file will (most likely) be part of the metadata page in RDMkit in end of May (after RDMkit contentathon), we could link to this page from ours and only have a short intro in ours (and perhaps give examples of other types of READMEs such as for SLL Figshare).

**Comment by YvonneKallberg** [comment]
The README text in RDMkit is now live: [https://rdmkit.elixir-europe.org/metadata_management#what-do-you-write-in-a-readme-file](https://rdmkit.elixir-europe.org/metadata_management#what-do-you-write-in-a-readme-file)
