### ISSUE TITLE
Add link to DM support

### ISSUE THREAD

**Issue by nicjar** [ScilifelabDataCentre/RDM-guidelines#6]
We should advertise data-management@scilifelab.se on the front page

**Comment by elinkronander** [comment]
We decided to do this by having a contact form

**Comment by LianeHughes** [comment]
Is all that is needed to finalise the contact form for this? I am unsure who set up the form for this but I can help out with finalising this (e.g. getting the ReCaptcha)

**Comment by nicjar** [comment]
We could start with a very simple form: Name, email, help needed.

Or we could think of a couple of broad topic categories to have in a drop-down menu as guidance to users (to help us with the sorting of requests).
