### ISSUE TITLE
Reduce space between SciLifeLab logo and "RDM Guidelines"

### ISSUE THREAD

**Issue by nicjar** [ScilifelabDataCentre/RDM-guidelines#70]
In e.g the header of the site there is a large space between the text _SciLifeLab_ of the logo and the text _RDM Guidelines_. These elements make up a joint object that links to the starting page. However, visually (at least to me) they appear to be separate entities. The SciLifeLab logo to me signals that if I click there, I will come to the main SciLifeLab site, which might cause some confusion. The same thing is true for the _Scilifelab Data Platform_ clickable object in the footer.

**Comment by LianeHughes** [comment]
Unfortunately, this is related to requirements of the scilifelab visual identity. We aren't allowed to put the 'RDM guidelines' or 'Data Platform' wording any closer to the logo. We have raised this with the appropriate department before, and will alter in future if it is possible to do so. Is this OK for now?

**Comment by elinkronander** [comment]
This will have to do for now
