### ISSUE TITLE
Contact form - reCAPTCHA

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#91]
Need to fix the reCAPTCHA, currently an error message 'Invalid domain for site key'

**Comment by LianeHughes** [comment]
Hi! I am on this I need to get a recaptcha for this URL and change the forms to go to the right places etc.

**Comment by YvonneKallberg** [comment]
I assumed you were, just created an issue to make sure it won't be forgotten :-)
